services:
  api:
    depends_on:
      - db
    build: .
    ports:
      - "4000:4000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
  db:
    image: "mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mood_tracker
      MYSQL_DATABASE_PASSWORD: root
      MYSQL_DATABASE_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root  
    volumes: 
      - ./mood_tracker.sql:/docker-entrypoint-initdb.d/mood_tracker.sql